In [2]:
import numpy as np
import pandas as pd
from scipy.stats import norm

Data taken from table 1 on page 48 of JP Morgan paper

So this is 
1. The smoothed historical average transition matrix
2. bins corresponding o smoothed historical average transition matrix

In [5]:
## smoothed observed transition matrix.
P = np.array([[91.13, 8, .7, .1, .05, .01, .01, .01 ]
             ,[.7, 91.03, 7.47, .6, .1, .07, .02, .01]
             ,[.1, 2.34, 91.54, 5.08, .61, 0.26, 0.01, 0.05]
             ,[0.02,0.3,5.65,87.98,4.75,1.05,0.1,0.15]
             ,[0.01,0.11,.55,7.77,81.77,7.95,0.85,1]
             ,[0,0.05,0.25,0.45,7,83.5,3.75,5]
             ,[0,0.01,.1,0.3,2.59,12,65,20]
             #,[0,0,0,0,0,0,0,100]
             ])

## predicted based on rho = 0.0163, z = -0.89
F = np.array([[89.35,9.54,0.89,0.13,0.07,0.01,0.01,0.01]
             ,[0.48,89.56,8.93,0.77,0.13,0.09,0.03,0.01]
             ,[0.06,1.72,90.88,6.14,0.78,0.34,0.01,0.07]
             ,[0.01,0.20,4.39,88.03,5.72,1.33,0.13,0.20]
             ,[0.00,0.07,0.38,6.19,81.63,9.39,1.06,1.29]
             ,[0.00,0.03,0.17,0.32,5.56,83.41,4.38,6.14]
             ,[0.00,0.01,0.06,0.20,1.94,10.09,64.53,23.16]
             #,[0,0,0,0,0,0,0,100]
             ])

## bins "based" on smooth transition matrix
interval_matrix = np.array([[np.Inf, -1.35,-2.38,-2.93,-3.19,-3.54,-3.72,-3.89,-np.Inf]
,[np.Inf,2.46,-1.39,-2.41,-2.88,-3.09,-3.43,-3.72,-np.Inf ]
,[np.Inf,3.1,1.97,-1.55,-2.35,-2.73,-3.24,-3.29 ,-np.Inf ]
,[np.Inf,3.5,2.73,1.56,-1.55,-2.23,-2.81,-2.97 ,-np.Inf ]
,[np.Inf,3.89,3.05,2.48,1.38,-1.29,-2.09,-2.33 ,-np.Inf ]
,[np.Inf,4.11,3.29,2.75,2.43,1.42,-1.36,-1.64 ,-np.Inf ]
,[np.Inf,4.27,3.72,3.06,2.64,1.88,1.04,-0.84 ,-np.Inf ]
])

n = np.array([ 85,220,480,298,168,161,16])

In [6]:
PN = (P / P.sum(axis=1)[:, np.newaxis]) 

In [7]:
pd.DataFrame(PN)

0         1         2         3         4         5         6  \
0  0.911209  0.079992  0.006999  0.001000  0.000500  0.000100  0.000100   
1  0.007000  0.910300  0.074700  0.006000  0.001000  0.000700  0.000200   
2  0.001000  0.023402  0.915492  0.050805  0.006101  0.002600  0.000100   
3  0.000200  0.003000  0.056500  0.879800  0.047500  0.010500  0.001000   
4  0.000100  0.001100  0.005499  0.077692  0.817618  0.079492  0.008499   
5  0.000000  0.000500  0.002500  0.004500  0.070000  0.835000  0.037500   
6  0.000000  0.000100  0.001000  0.003000  0.025900  0.120000  0.650000   

          7  
0  0.000100  
1  0.000100  
2  0.000500  
3  0.001500  
4  0.009999  
5  0.050000  
6  0.200000

In [100]:
## working from the provided interval matrix to the transition matrix and back

In [8]:
p = pd.DataFrame(norm.cdf(interval_matrix)).diff(axis=1)*-1
p = p.values[:,1:]

In [9]:
p_fliplr = np.fliplr(p)
p_cumsum = np.fliplr(p_fliplr.cumsum(axis=1))

In [10]:
my_interval_matrix = norm.ppf(p_cumsum)
my_interval_matrix = np.concatenate( (my_interval_matrix, -np.Inf*np.ones([p.shape[0],1])),axis=1)

In [11]:
my_interval_matrix

array([[  inf, -1.35, -2.38, -2.93, -3.19, -3.54, -3.72, -3.89,  -inf],
       [  inf,  2.46, -1.39, -2.41, -2.88, -3.09, -3.43, -3.72,  -inf],
       [  inf,  3.1 ,  1.97, -1.55, -2.35, -2.73, -3.24, -3.29,  -inf],
       [  inf,  3.5 ,  2.73,  1.56, -1.55, -2.23, -2.81, -2.97,  -inf],
       [  inf,  3.89,  3.05,  2.48,  1.38, -1.29, -2.09, -2.33,  -inf],
       [  inf,  4.11,  3.29,  2.75,  2.43,  1.42, -1.36, -1.64,  -inf],
       [  inf,  4.27,  3.72,  3.06,  2.64,  1.88,  1.04, -0.84,  -inf]])

In [31]:
print("table 1\n")
print("The smoothed historical average transition matrix\n",pd.DataFrame(P/100),"\n")
print("bins corresponding o smoothed historical average transition matrix\n",np.round(interval_matrix,3))

table 1

The smoothed historical average transition matrix
         0       1       2       3       4       5       6       7
0  0.9113  0.0800  0.0070  0.0010  0.0005  0.0001  0.0001  0.0001
1  0.0070  0.9103  0.0747  0.0060  0.0010  0.0007  0.0002  0.0001
2  0.0010  0.0234  0.9154  0.0508  0.0061  0.0026  0.0001  0.0005
3  0.0002  0.0030  0.0565  0.8798  0.0475  0.0105  0.0010  0.0015
4  0.0001  0.0011  0.0055  0.0777  0.8177  0.0795  0.0085  0.0100
5  0.0000  0.0005  0.0025  0.0045  0.0700  0.8350  0.0375  0.0500
6  0.0000  0.0001  0.0010  0.0030  0.0259  0.1200  0.6500  0.2000 

bins corresponding o smoothed historical average transition matrix
 [[  inf -1.35 -2.38 -2.93 -3.19 -3.54 -3.72 -3.89  -inf]
 [  inf  2.46 -1.39 -2.41 -2.88 -3.09 -3.43 -3.72  -inf]
 [  inf  3.1   1.97 -1.55 -2.35 -2.73 -3.24 -3.29  -inf]
 [  inf  3.5   2.73  1.56 -1.55 -2.23 -2.81 -2.97  -inf]
 [  inf  3.89  3.05  2.48  1.38 -1.29 -2.09 -2.33  -inf]
 [  inf  4.11  3.29  2.75  2.43  1.42 -1.36 -1.64  -inf]


In [32]:
print("table 1\n")
print("The smoothed historical average transition matrix\n",np.round(pd.DataFrame(p),4),"\n")
print("bins corresponding o smoothed historical average transition matrix\n",np.round(my_interval_matrix,3))

table 1

The smoothed historical average transition matrix
         0       1       2       3       4       5       6       7
0  0.9115  0.0799  0.0070  0.0010  0.0005  0.0001  0.0000  0.0001
1  0.0069  0.9108  0.0743  0.0060  0.0010  0.0007  0.0002  0.0001
2  0.0010  0.0235  0.9150  0.0512  0.0062  0.0026  0.0001  0.0005
3  0.0002  0.0029  0.0562  0.8800  0.0477  0.0104  0.0010  0.0015
4  0.0001  0.0011  0.0054  0.0772  0.8177  0.0802  0.0084  0.0099
5  0.0000  0.0005  0.0025  0.0046  0.0703  0.8353  0.0364  0.0505
6  0.0000  0.0001  0.0010  0.0030  0.0259  0.1191  0.6504  0.2005 

bins corresponding o smoothed historical average transition matrix
 [[  inf -1.35 -2.38 -2.93 -3.19 -3.54 -3.72 -3.89  -inf]
 [  inf  2.46 -1.39 -2.41 -2.88 -3.09 -3.43 -3.72  -inf]
 [  inf  3.1   1.97 -1.55 -2.35 -2.73 -3.24 -3.29  -inf]
 [  inf  3.5   2.73  1.56 -1.55 -2.23 -2.81 -2.97  -inf]
 [  inf  3.89  3.05  2.48  1.38 -1.29 -2.09 -2.33  -inf]
 [  inf  4.11  3.29  2.75  2.43  1.42 -1.36 -1.64  -inf]


In [117]:
## number of observations for each credit reating
n = np.array([ 85,220,480,298,168,161,16])

Below, I calculate my own bins corresponding o smoothed historical average transition matrix

## The continuous credit-change indicator

Binning of this indicator is based on the estimated transaction matrix.  

My calculations

In [33]:
print("my calc for bins corresponding to smoothed historical average transition matrix")
print(np.round(my_interval_matrix,2))

my calc for bins corresponding to smoothed historical average transition matrix
[[  inf -1.35 -2.38 -2.93 -3.19 -3.54 -3.72 -3.89  -inf]
 [  inf  2.46 -1.39 -2.41 -2.88 -3.09 -3.43 -3.72  -inf]
 [  inf  3.1   1.97 -1.55 -2.35 -2.73 -3.24 -3.29  -inf]
 [  inf  3.5   2.73  1.56 -1.55 -2.23 -2.81 -2.97  -inf]
 [  inf  3.89  3.05  2.48  1.38 -1.29 -2.09 -2.33  -inf]
 [  inf  4.11  3.29  2.75  2.43  1.42 -1.36 -1.64  -inf]
 [  inf  4.27  3.72  3.06  2.64  1.88  1.04 -0.84  -inf]]


Directly transscribed from the paper

In [34]:
print("orig paper calc for bins corresponding to smoothed historical average transition matrix")
print(interval_matrix)

orig paper calc for bins corresponding to smoothed historical average transition matrix
[[  inf -1.35 -2.38 -2.93 -3.19 -3.54 -3.72 -3.89  -inf]
 [  inf  2.46 -1.39 -2.41 -2.88 -3.09 -3.43 -3.72  -inf]
 [  inf  3.1   1.97 -1.55 -2.35 -2.73 -3.24 -3.29  -inf]
 [  inf  3.5   2.73  1.56 -1.55 -2.23 -2.81 -2.97  -inf]
 [  inf  3.89  3.05  2.48  1.38 -1.29 -2.09 -2.33  -inf]
 [  inf  4.11  3.29  2.75  2.43  1.42 -1.36 -1.64  -inf]
 [  inf  4.27  3.72  3.06  2.64  1.88  1.04 -0.84  -inf]]


There are bound to be differences between due to rounding.  The primary function used to derive the bins has a very  steep slope which would imply that small changed in the input result in large changes in the output.  So when they are rounded the values they report, it has a significant impact on my binning.  

In [63]:
A = np.array([[1,2], [5,6]])
A / A.sum(axis=1)[:, np.newaxis]

array([[ 0.33333333,  0.66666667],
       [ 0.45454545,  0.54545455]])

In [62]:
for z in np.linspace(-1, 1, 10):
    phat = fitted_probs(z, 0.0163, interval_matrix)
    c = np.sum((p - phat)**2 / (phat * (1 - phat)) * n[:, np.newaxis]) 
    print(z,",", c)

-1.0 , 12.3185487563
-0.777777777778 , 7.32697865176
-0.555555555556 , 3.67941938672
-0.333333333333 , 1.3419151178
-0.111111111111 , 0.287806391639
0.111111111111 , 0.498228356292
0.333333333333 , 1.96261947452
0.555555555556 , 4.67922015832
0.777777777778 , 8.6555430828
1.0 , 13.9088007393


In [66]:
n[:, np.newaxis]

array([[ 85],
       [220],
       [480],
       [298],
       [168],
       [161],
       [ 16]])

## Fitted Transition matrix vs Observed

I'm not including the least squares fit (i haven't done it yet), but that part is the most straight forward in my opinion.

In [35]:
def fitted_probs(z, rho, interval_matrix):
    temp = (interval_matrix - np.sqrt(rho)*z) / np.sqrt(1-rho)  
    fit = np.zeros_like(interval_matrix)
    for i in range(fit.shape[0]+1):
        fit[:,i] = norm.cdf(temp[:,i]) - norm.cdf(temp[:,i+1])
    return fit[:,0:-1]

In [40]:
pd.DataFrame(fitted_probs(-0.89,0.0163,my_interval_matrix))

0         1         2         3         4         5         6  \
0  0.893723  0.095123  0.008896  0.001297  0.000686  0.000137  0.000068   
1  0.004731  0.896205  0.088766  0.007656  0.001296  0.000932  0.000275   
2  0.000597  0.017231  0.908394  0.061705  0.007902  0.003360  0.000129   
3  0.000135  0.001937  0.043688  0.880463  0.057349  0.013150  0.001289   
4  0.000027  0.000685  0.003749  0.061579  0.816165  0.094647  0.010428   
5  0.000010  0.000290  0.001643  0.003221  0.055854  0.834543  0.042533   
6  0.000005  0.000051  0.000632  0.002061  0.019463  0.100174  0.645642   

          7  
0  0.000070  
1  0.000138  
2  0.000681  
3  0.001989  
4  0.012720  
5  0.061906  
6  0.231973

In [42]:
pd.DataFrame(F/100)

0       1       2       3       4       5       6       7
0  0.8935  0.0954  0.0089  0.0013  0.0007  0.0001  0.0001  0.0001
1  0.0048  0.8956  0.0893  0.0077  0.0013  0.0009  0.0003  0.0001
2  0.0006  0.0172  0.9088  0.0614  0.0078  0.0034  0.0001  0.0007
3  0.0001  0.0020  0.0439  0.8803  0.0572  0.0133  0.0013  0.0020
4  0.0000  0.0007  0.0038  0.0619  0.8163  0.0939  0.0106  0.0129
5  0.0000  0.0003  0.0017  0.0032  0.0556  0.8341  0.0438  0.0614
6  0.0000  0.0001  0.0006  0.0020  0.0194  0.1009  0.6453  0.2316

In [43]:
rhos = [0.0163, 0.02, 0.03]

def cost(z):
    fit = fitted_probs(z,0.0163, interval_matrix)
    return np.sum( ((P/100 - fit)**2) * n[:, np.newaxis] / ( fit * (1 - fit)))

#cost = lambda z: (P - fitted_probs(z, 0.0163, interval_matrix))**2 

In [124]:

np.sum((P/100 - fitted_probs(-0.0,0.0163, interval_matrix))**2 * n[:, np.newaxis])

0.015585267439948799

Below I use all the data from the paper to do the predictions with my function.  

These outputs correspond to the Fitted Transition Matrix in Table 2 on page 50

<img src="capture.png">

In [48]:
predicted = fitted_probs(-0.89, 0.0163, interval_matrix)
print(np.round(predicted,3)*100)

[[ 89.4   9.5   0.9   0.1   0.1   0.    0.    0. ]
 [  0.5  89.6   8.9   0.8   0.1   0.1   0.    0. ]
 [  0.1   1.7  90.8   6.2   0.8   0.3   0.    0.1]
 [  0.    0.2   4.4  88.    5.7   1.3   0.1   0.2]
 [  0.    0.1   0.4   6.2  81.6   9.5   1.    1.3]
 [  0.    0.    0.2   0.3   5.6  83.5   4.3   6.2]
 [  0.    0.    0.1   0.2   1.9  10.   64.6  23.2]]


Below I use my derived interval matrix (filling in the bad value with -3.89)

In [49]:
my_predicted = fitted_probs(-0.89, 0.0163, my_interval_matrix)
print(np.round(my_predicted,3)*100)

[[ 89.4   9.5   0.9   0.1   0.1   0.    0.    0. ]
 [  0.5  89.6   8.9   0.8   0.1   0.1   0.    0. ]
 [  0.1   1.7  90.8   6.2   0.8   0.3   0.    0.1]
 [  0.    0.2   4.4  88.    5.7   1.3   0.1   0.2]
 [  0.    0.1   0.4   6.2  81.6   9.5   1.    1.3]
 [  0.    0.    0.2   0.3   5.6  83.5   4.3   6.2]
 [  0.    0.    0.1   0.2   1.9  10.   64.6  23.2]]


It is pretty close in my opinion.

## Determinining Transition Matrices as Functions of Z-score

Page 54 of the JP Morgan Paper

In [50]:
print("all calcs based on bins taken directly from paper")
good_year = fitted_probs(1, 0.0163, interval_matrix)
average_year = fitted_probs(0, 0.0163, interval_matrix)
bad_year = fitted_probs(-1, 0.0163, interval_matrix)
print("good year\n", np.round(good_year,3)*100, "\n")
print("average year\n",np.round(average_year,3)*100,"\n")
print("bad year\n", np.round(bad_year,3)*100, "\n")

all calcs based on bins taken directly from paper
good year
 [[ 93.2   6.2   0.5   0.1   0.    0.    0.    0. ]
 [  0.9  92.8   5.8   0.4   0.1   0.    0.    0. ]
 [  0.1   3.   92.3   3.9   0.4   0.2   0.    0. ]
 [  0.    0.4   7.   88.    3.7   0.7   0.1   0.1]
 [  0.    0.2   0.7   9.5  82.    6.4   0.6   0.7]
 [  0.    0.1   0.3   0.6   8.6  83.7   2.9   3.7]
 [  0.    0.    0.1   0.4   3.3  14.   65.7  16.5]] 

average year
 [[ 91.3   7.9   0.7   0.1   0.    0.    0.    0. ]
 [  0.7  91.3   7.3   0.6   0.1   0.1   0.    0. ]
 [  0.1   2.3  91.7   5.    0.6   0.2   0.    0. ]
 [  0.    0.3   5.5  88.3   4.7   1.    0.1   0.1]
 [  0.    0.1   0.5   7.6  82.1   7.9   0.8   0.9]
 [  0.    0.    0.2   0.4   6.9  83.9   3.6   4.9]
 [  0.    0.    0.1   0.3   2.5  11.8  65.4  19.9]] 

bad year
 [[ 89.1   9.7   0.9   0.1   0.1   0.    0.    0. ]
 [  0.5  89.4   9.1   0.8   0.1   0.1   0.    0. ]
 [  0.1   1.7  90.7   6.3   0.8   0.3   0.    0.1]
 [  0.    0.2   4.2  88.    5.9   1.4   0.

In [51]:
print("all my calcs")
good_year = fitted_probs(1, 0.0163, my_interval_matrix)
average_year = fitted_probs(0, 0.0163, my_interval_matrix)
bad_year = fitted_probs(-1, 0.0163, my_interval_matrix)
print("good year\n", np.round(good_year,3)*100, "\n")
print("average year\n",np.round(average_year,3)*100,"\n")
print("bad year\n", np.round(bad_year,3)*100, "\n")

all my calcs
good year
 [[ 93.2   6.2   0.5   0.1   0.    0.    0.    0. ]
 [  0.9  92.8   5.8   0.4   0.1   0.    0.    0. ]
 [  0.1   3.   92.3   3.9   0.4   0.2   0.    0. ]
 [  0.    0.4   7.   88.    3.7   0.7   0.1   0.1]
 [  0.    0.2   0.7   9.5  82.    6.4   0.6   0.7]
 [  0.    0.1   0.3   0.6   8.6  83.7   2.9   3.7]
 [  0.    0.    0.1   0.4   3.3  14.   65.7  16.5]] 

average year
 [[ 91.3   7.9   0.7   0.1   0.    0.    0.    0. ]
 [  0.7  91.3   7.3   0.6   0.1   0.1   0.    0. ]
 [  0.1   2.3  91.7   5.    0.6   0.2   0.    0. ]
 [  0.    0.3   5.5  88.3   4.7   1.    0.1   0.1]
 [  0.    0.1   0.5   7.6  82.1   7.9   0.8   0.9]
 [  0.    0.    0.2   0.4   6.9  83.9   3.6   4.9]
 [  0.    0.    0.1   0.3   2.5  11.8  65.4  19.9]] 

bad year
 [[ 89.1   9.7   0.9   0.1   0.1   0.    0.    0. ]
 [  0.5  89.4   9.1   0.8   0.1   0.1   0.    0. ]
 [  0.1   1.7  90.7   6.3   0.8   0.3   0.    0.1]
 [  0.    0.2   4.2  88.    5.9   1.4   0.1   0.2]
 [  0.    0.1   0.4   6.   8